config/routes.rb
Mafoto::Application.routes.draw do
  root :to => "main#index"
  resources :photos do 
    resources :comments
  end 

  resources :groups

  devise_for :users

  get "main/index"

  get "main/about"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :photo_id, :user_id
  belongs_to :user
  belongs_to :photo 
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
  has_many :photos, :dependent => :destroy
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :group_id, :name, :user_id, :picture
  belongs_to :group
  belongs_to :user
  has_many :comments

  has_attached_file :picture,
  	:styles => { :medium => "300x300>", :thumb => "100x100>" },
  	:storage => :dropbox,
  	:dropbox_credentials => "#{Rails.root}/config/dropbox_config.yml",
  	:dropbox_options => {       
		:path => proc { |style| "#{style}/#{id}_#{picture.original_filename}"}, :unique_filename => true   
 	}

 	validates :picture, :attachment_presence => true 
 	validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :groups, :dependent => :destroy
  has_many :photos
  has_many :comments
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :authenticate_user!

	def create
		@photo = Photo.find(params[:photo_id])
		@comment = @photo.comments.create(params[:comment])
		redirect_to photo_path(@photo)
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.order("name").page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = current_user.groups.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = current_user.groups.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = current_user.groups.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.order("name").page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new(:group_id => params[:group_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo.group, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>


<% @groups.each do |group| %>
    <%= link_to group.name, group %>
    <%= link_to 'Edit', edit_group_path(group) %> |
    <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %><br ><br />
<% end %>

<br />

<%= paginate @groups %>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Created by:</b>
  <%= @group.user.name %>
</p>

<p><%= link_to 'Add Photos', new_photo_path(:group_id => @group.id) %></p>

<p>
	<h4>Photos in this group</h4>
	<% @group.photos.each do |photo| %>
		<h5><%= photo.name %></h5>
		<small><em>Uploaded by: <%= photo.user.name%></em></small><br /><br />
		<%= image_tag photo.picture.url %><br /><br />
		<%= link_to "Comment on photo", photo %>
	<% end %>
</p>
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/_header.html.erb
<span class="header_logo">Mafoto</span>
<ul class="top_links">
	<li><%= link_to "Home", root_url %></li>
	<li><%= link_to "About"%></li>
	<% if user_signed_in? %>
		<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
	<% else %>
		<li><%= link_to "Sign In", new_user_session_path %></li>
	<% end %>
	<% if user_signed_in? %>
		<li><%= link_to "Edit Account", edit_user_registration_path %></li>
	<% else %>
		<li><%= link_to "Sign Up", new_user_registration_path %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mafoto: Share Photos With Friends</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="header">
		<%= render :partial => "layouts/header" %>
	</div>
	<div class="container">
		<p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
		<%= yield %>
	</div>

</body>
</html>

app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/index.html.erb
<p>Share photos with friends</p>


<%= link_to "See Groups", groups_path %>

app/views/photos/_form.html.erb
<%= form_for @photo, :html => {:multipart => true}  do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :group_id, :value => params[:group_id] %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
   <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <p>
  <div class="actions">
    <%= f.submit %>
  </div>
</p>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.name %></td>
    <td><%= photo.user_id %></td>
    <td><%= photo.group_id %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p>
  <b>Name:</b>
  <%= @photo.name %>
</p>
	<%= image_tag @photo.picture.url(:medium) %>
<p>

</p>
<h4><%= @photo.comments.size %></h4>
<% if @photo.comments.nil? %>
	<em>No comments yet!</em>
<% else %>
	<% @photo.comments.each do |comment| %>
		<i><b><small><%= time_ago_in_words(comment.created_at)%> ago</b><br />
		<%= comment.user.name %> said:</small></i><br /><br />
		<%= comment. body %><br /><br />
		<hr />
	<% end %>
<% end %>

<%= form_for([@photo, @photo.comments.build]) do |f| %>
	<p>
		<%= f.hidden_field :user_id, :value => current_user.id %>
	</p>
	<p>
		<%= f.text_area :body, :rows => 10 %>
	</p>
	<p>
		<%= f.submit "Add Comment" %>
	</p>
<% end %>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>